print()
print("#-------'#######---###  ----  ######  --___----######_--  --####___--- ")
print("#-       ---                                       ---          ---")
print(" ##               ~~~map of the maze of secrets~~~                      l")
print("##        ~~use with caution~~~                                          |")
print("|                                     ####____ _____ ----____--_        l")
print("|                                     #           |     --    l        l")
print("|                                      #           |           l      |")
print("|                                      |   castle  |  treasury |       #")
print("|                                      l           |          l      ##")
print("  |                                   l           l           |        #")
print("  |         ##____________-------------________###---------__ #        #")
print("  #      |         l         |         l          #          l        l")
print("  #      #          |          | haunted l          #         |        l")
print("  #      l    cave   |  mine   |  house  l  library l  forest |       ##")
print(" #       #          |         l          l          |          #        |")
print(" ##      l          #         l          l          |           #       #")
print(" l       ####--------#  _ ____l  ___  _l  ____    |## ________###        #")
print("l                                                                        #")
print("  l                                                                      #")
print("l                                                                         |")
print("#             ___                           __              ______##     l")
print("--###______--##__#####___-  ####  ---######-#-   ----___==######----    -- ")
print()

print()
print("#-------'#######---###  ----  ######  --___----######_--  --####___--- ")
print("#-       ---                                       ---          ---")
print(" ##               ~~~map of the maze of secrets~~~                      l")
print("##        ~~use with caution~~~                                          |")
print("|                                     ####____ _____ ----____--_        l")
print("|                                     #           |     --    |        l")
print("|                                     #           |           |        l")
print("|                                     |   castle  |  treasury |        l")
print("|                                     l           |          l        l")
print("  |                                   l           l           |        l")
print("  |         ##____________-------------________###---------__ #        l")
print("  #      |         l         |         l          #          l        l")
print("  #      #          |          | haunted l          #         |        l")
print("  #      l    cave   |  mine   |  house  l  library l  forest |       l")
print(" #       #          |         l          l          |          #        l")
print(" ##      l          #         l          l          |           #       l")
print(" l       ####--------#  _ ____l  ___  _l  ____    |## ________###        l")
print("l                                                                        l")
print("  l                                                                      l")
print("l                                                                         l")
print("#             ___                           __              ______##     l")
print("--###______--##__#####___-  ####  ---######-#-   ----___==######----    -- ")
print()
